[WIP] DLPJTS-116 custom signature label
datalogics/pdf-java-toolkit-samples pull request #112
Opened 2017-06-06 20:51 UTC by datalogics-kam

#### Changes in this pull request

- Use a unicode character in the signature.
- Embed a font and show that Type 0 fonts are subset.

#### Fulfills  DLPJTS-116](https://jira.datalogics.com/browse/DLPJTS-116)

#### Checklist for approving this pull request

(PR creator amend this with more conditions if necessary)

- [ ] There are **unit tests** for new/changed code, or a good explanation why this was not possible.
- [ ] All **CI builders** have indicated success (Give them a few minutes to notice the pull request.)
- [ ] The **Pull request title** has the JIRA issue numbers separated by spaces (if any), a space, and then a short, but descriptive summary.
- [ ] **Commit messages** are well formed: [A note about Git commit messages](http://www.tpope.net/node/106)
- [ ] New public packages, classes, and methods are **documented**. (Strongly consider documenting private classes and methods.)

#### Blockers

Add a checkbox for yourself with your **&#64;name** to this list if you are holding this PR open for review. PR Shepherd, please hold off merging this PR until these are all checked:

- [x] _&lt;add your name here with an **@**>_

2017-06-06 20:53 UTC, datalogics-devauto commented
Build failed.

2017-06-06 20:53 UTC, datalogics-devauto commented
Build failed.

2017-06-07 19:50 UTC, datalogics-devauto commented
Build failed.

2017-06-07 19:50 UTC, datalogics-devauto commented
Build failed.

2017-06-07 23:00 UTC, datalogics-devauto commented
Build failed.

2017-06-07 23:00 UTC, datalogics-devauto commented
Build failed.

2017-06-08 16:28 UTC, datalogics-devauto commented
Build failed.

2017-06-08 16:28 UTC, datalogics-devauto commented
Build failed.

2017-06-08 17:09 UTC, datalogics-devauto commented
Build failed.

2017-06-08 17:09 UTC, datalogics-devauto commented
Build failed.

2017-06-09 15:28 UTC, datalogics-devauto commented
Build failed.

2017-06-09 15:28 UTC, datalogics-devauto commented
Build failed.

2017-06-09 16:41 UTC, datalogics-kam commented
trigger build

2017-06-09 16:44 UTC, datalogics-devauto commented
Build succeeded.

2017-06-09 16:44 UTC, datalogics-devauto commented
Build succeeded.

2017-06-09 17:06 UTC, datalogics-kam commented
@datalogics-coreyy This is ready to go.

2017-06-12 13:17 UTC, datalogics-bhaugen commented on src/main/java/com/datalogics/pdf/samples/signature/SignDocument.java
> +    // signer, which is taken from the UserInfo.name in the
Looks like there is something missing from this sentence in the documentation

2017-06-12 15:19 UTC, datalogics-kam commented on src/main/java/com/datalogics/pdf/samples/signature/SignDocument.java
> +    // signer, which is taken from the UserInfo.name in the
Thanks. I fixed it up and also pulled up the signer name.

2017-06-12 15:21 UTC, datalogics-devauto commented
Build succeeded.

2017-06-12 15:22 UTC, datalogics-devauto commented
Build succeeded.

2017-06-12 15:27 UTC, datalogics-coreyy commented on src/main/java/com/datalogics/pdf/samples/util/DocumentUtils.java
> +    public static List<RasterContentItem> getFormContentItems(final PDFPage page, final PDFXObjectForm form,
Nice! This is going to be really useful

2017-06-12 15:57 UTC, datalogics-coreyy requested changes

2017-06-12 15:57 UTC, datalogics-coreyy commented on src/test/java/com/datalogics/pdf/samples/util/ContentTextItemMatchers.java
> + * Copyright 2015 Datalogics, Inc.
Date should be 2017

2017-06-12 15:57 UTC, datalogics-coreyy commented on src/test/java/com/datalogics/pdf/samples/signature/SignDocumentTest.java
> +    private List<ContentTextItem<?, ?>> getContentTextItems(XObject overlayTextForm) {
I might call 'overlayTextForm' something else here like 'signatureAppearanceForm' maybe?

2017-06-12 15:57 UTC, datalogics-coreyy commented on src/main/java/com/datalogics/pdf/samples/signature/SignDocument.java
> +    // signer, which is taken from the UserInfo.name in the
I think @datalogics-bhaugen was referring to line 79 ', which is taken from the UserInfo.name in the'

2017-06-12 15:57 UTC, datalogics-coreyy commented on src/test/java/com/datalogics/pdf/samples/signature/SignDocumentTest.java
> +    private static void ensureDocument() throws Exception {
I think you could call ensureDocument in setUpDocument. Then you can avoid calling ensureDocument 3 times for each test. They don't seem to be manipulating the document so it should be okay.

2017-06-12 15:57 UTC, datalogics-coreyy commented on src/test/java/com/datalogics/pdf/samples/signature/SignDocumentTest.java
> +    private List<ContentTextItem<?, ?>> getContentTextItems(XObject overlayTextForm) {
Eh I guess it really doesn't matter...update at your discretion

2017-06-12 19:13 UTC, datalogics-kam commented on src/test/java/com/datalogics/pdf/samples/signature/SignDocumentTest.java
> +    private static void ensureDocument() throws Exception {
Actually, I don't want to do all that work in `setUpDocument` for a few reasons:

* The tests are timed, but the setup is not, so you can't tell how much time it took to set up the document by looking in the IDE
* Errors thrown during setup are hard to understand and diagnose

So I just have the first test that runs make the document.

2017-06-12 19:18 UTC, datalogics-kam commented on src/test/java/com/datalogics/pdf/samples/util/ContentTextItemMatchers.java
> + * Copyright 2015 Datalogics, Inc.
Got it, thanks!

2017-06-12 19:22 UTC, datalogics-devauto commented
Build succeeded.

2017-06-12 19:22 UTC, datalogics-devauto commented
Build succeeded.

2017-06-12 21:26 UTC, datalogics-coreyy approved these changes

2017-06-13 15:52 UTC, datalogics-coreyy requested changes

2017-06-13 15:52 UTC, datalogics-coreyy commented on src/main/java/com/datalogics/pdf/samples/signature/SignDocument.java
> +                    appearanceOptions.setSignatureLabel(SIGNATURE_LABEL);
Eclipse can't find this recently added 'setSignatureLabel'. I think you need to exclude this from the Talkeetna 5 build like we did with the export to csv sample.

2017-06-13 16:13 UTC, datalogics-kam commented on src/main/java/com/datalogics/pdf/samples/signature/SignDocument.java
> +                    appearanceOptions.setSignatureLabel(SIGNATURE_LABEL);
Oooh, good catch.

2017-06-13 19:13 UTC, datalogics-devauto commented
Build succeeded.

2017-06-13 19:13 UTC, datalogics-devauto commented
Build succeeded.

2017-06-13 20:12 UTC, datalogics-devauto commented
Build succeeded.

2017-06-13 20:12 UTC, datalogics-devauto commented
Build succeeded.

2017-06-13 21:14 UTC, datalogics-devauto commented
Build succeeded.

2017-06-13 21:14 UTC, datalogics-devauto commented
Build succeeded.

2017-06-13 21:27 UTC, datalogics-coreyy approved these changes

2017-06-13 21:28 UTC, merged